### ISSUE TITLE
Colour

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk_design_prototypes#3]
Discussion about the [colour design pattern](https://gentle-crag-56748.herokuapp.com/v3/styles/colour)

**Comment by gavinwye** [comment]
Is colour a design pattern? I'd see it as one of the framework/basic things

**Comment by timpaul** [comment]
I think this is something we need to decide - do we split out the 'Styles' category into basic elements versus more fundamental things like colour swatches, grids, dimensions, utility classes etc. I'll make sure we have a version of the prototype that slices things that when when we start doing some user research. I expect we'll do some card sorting as well at some point.
